package com.stellarcompact.api.galaxy;

/**
 * Computes the strong HTTP {@code ETag} validator for a tile, keyed by
 * {@code (gameSeed, level, x, y, schemaVersion)} (rest-api spec; lod-tiling
 * skill: "ETag by (seed,level,x,y,schemaVersion)").
 *
 * <p>The ETag depends only on the address + schema, not on the generated bytes -
 * but because the tile is a pure function of exactly those inputs, the validator
 * is sound: identical address+schema always means identical content, so a match
 * legitimately yields {@code 304 Not Modified}. Computing it from the key avoids
 * generating the (potentially large) payload just to answer a conditional GET.
 *
 * <p>Deterministic across calls and JVMs: same inputs -> same quoted hex string.
 */
public final class TileEtag {

    private TileEtag() {
    }

    /**
     * @return a strong ETag, already wrapped in double quotes per RFC 9110
     *         (e.g. {@code "5-3-2-1-1f4a3c"} style hex). Strong (no {@code W/}).
     */
    public static String of(long gameSeed, int level, int x, int y, int schemaVersion) {
        // Mix the five components into a 64-bit value (SplitMix-style finaliser),
        // independent of platform, then render as hex. Order-sensitive so two
        // different addresses can't collide on a trivial sum.
        long h = 0x9E3779B97F4A7C15L;
        h = step(h, gameSeed);
        h = step(h, level);
        h = step(h, x);
        h = step(h, y);
        h = step(h, schemaVersion);
        return "\"" + Long.toHexString(h) + "\"";
    }

    private static long step(long acc, long v) {
        long z = acc + 0x9E3779B97F4A7C15L + v;
        z = (z ^ (z >>> 30)) * 0xBF58476D1CE4E5B9L;
        z = (z ^ (z >>> 27)) * 0x94D049BB133111EBL;
        return z ^ (z >>> 31);
    }
}
